### ISSUE TITLE
after making node as validator it works for couple seconds then crush

### ISSUE THREAD

**Issue by psixoz-korvin** [CasperLabs/casper-node#1029]
node version 1_0_0
Suppose that stop state issued by:
"node panicked: Bootstrap failed for node, but it was not in the set of pending connections
Error: "/var/lib/casper/bin/1_0_0/casper-node" "validator" "/etc/casper/1_0_0/config.toml" exited with error"
Using white IP and VDS. ufw disabled. Ubuntu 20.04

[casper-node.stderr.log](https://github.com/CasperLabs/casper-node/files/6057105/casper-node.stderr.log)node

![image](https://user-images.githubusercontent.com/53143629/109425061-8169a700-79f7-11eb-827c-a7eb42c0dd36.png)

[casper-node.log](https://github.com/CasperLabs/casper-node/files/6057104/casper-node.log)

**Comment by goral09** [comment]
Thank you for submitting the issue. The solution is to look at the `known_addresses` in the config file and look for duplicate entries. Removing duplicates solves the problem.
