### ISSUE TITLE
Finalized block that hasn't been proposed

### ISSUE THREAD

**Issue by trader-payne** [CasperLabs/casper-node#522]
Logs:
[casper-logs.log](https://github.com/CasperLabs/casper-node/files/5524837/casper-logs.log)

This `Finalized block that hasn't been proposed` error started showing up after I raised my bid in the auction.

Logs after restarting the node:
https://pastebin.com/a0GUqhzZ

System specs:
AMD Ryzen 9 3900 12c/24t
128GB DDR4 ECC
2x 2TB NVMe SSDs RAID0

**Comment by afck** [comment]
It's probably harmless. Will be addressed as part of https://github.com/CasperLabs/ceps/pull/20.

**Comment by goral09** [comment]
@trader-payne Can you verify if the problem still occurs? According to our best knowledge it has been fixed.

**Comment by MParlikar** [comment]
Closing - we believe the issue has been fixed, and it hasn't appeared again.
