### ISSUE TITLE
Gossiper on rampage

### ISSUE THREAD

**Issue by matsuro-hadouken** [CasperLabs/casper-node#523]
Observing last 6 hours on my monitoring solution, I notice table items are significantly increased.
First thoughts it was someone spamming allot of deploys, but observing deploys count I figure out this is not the issue.

Here is some screenshots from my monitor ( 6 hour frame ):

Items finished:
![image](https://user-images.githubusercontent.com/50751381/98852697-f49edb80-244f-11eb-8ee3-fccbd9ded45f.png)

Items current:
![image](https://user-images.githubusercontent.com/50751381/98852749-0aac9c00-2450-11eb-9d83-75acd3916072.png)

Deploys onward:
![image](https://user-images.githubusercontent.com/50751381/98852801-1e580280-2450-11eb-920c-a4c8f29b19f0.png)

Table items finished:
![image](https://user-images.githubusercontent.com/50751381/98852955-5cedbd00-2450-11eb-9a14-09d22f1f8e42.png)

Unpleasant consequences:

CPU utilization:
![image](https://user-images.githubusercontent.com/50751381/98853079-84dd2080-2450-11eb-9fb2-25bea07dd15c.png)

Memory usage:
![image](https://user-images.githubusercontent.com/50751381/98853105-8f97b580-2450-11eb-9fcf-451b8ee90a5f.png)

Interrupts/s:
![image](https://user-images.githubusercontent.com/50751381/98853133-99b9b400-2450-11eb-8968-5be50764f164.png)

On load average we can observe strange behavior where in same 6 hours time frame 5 and 15 minutes decrease, but small momentum 1 minute spikes is growing.

![image](https://user-images.githubusercontent.com/50751381/98853354-e604f400-2450-11eb-970f-fb6ecf4ba70c.png)

Some stepped memory decrease ( is upside down in zabbix ):
![image](https://user-images.githubusercontent.com/50751381/98853470-1cdb0a00-2451-11eb-9ef0-41fb293674a5.png)

**Comment by matsuro-hadouken** [comment]
Some portional incoming packages here as well, this is zoom 1 hour:
![image](https://user-images.githubusercontent.com/50751381/98855219-8e1bbc80-2453-11eb-8513-a887f81a6b9c.png)

And here is 6 hours frame:
![image](https://user-images.githubusercontent.com/50751381/98855256-9e339c00-2453-11eb-96dc-22345a910e40.png)

**Comment by Fraser999** [comment]
This should be fixed by #697.
