### ISSUE TITLE
Weird behavior on genesis generation. After "Consensus(Shutdown)" node shutdown.

### ISSUE THREAD

**Issue by matsuro-hadouken** [CasperLabs/casper-node#566]
On the start of the Delta - 3 exact on the moment of genesis generation, my validator lost peers.

Status replay:
``` json
{
  "api_version": "1.0.0",
  "chainspec_name": "casper-delta-3",
  "genesis_root_hash": "e81d..b4c0",
  "peers": {},
  "last_added_block_info": null,
  "build_version": "1.6.0"
}
```
Expected:
``` json
{
    "api_version": "1.0.0",
    "chainspec_name": "casper-delta-3",
    "genesis_root_hash": "e81d..b4c0",
    "peers": {
        "45cf..1364": "13.57.242.68:35000",
        "4e5d..4e53": "194.19.235.78:35000",
        "716d..9a06": "167.99.74.47:35000",
        "db09..0b9b": "54.183.27.75:35000",
        "e52c..55ac": "207.180.221.204:35000"
    },
    "last_added_block_info": null,
    "build_version": "1.6.0"
}
```

1. Error

``` json
24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/liballoc/boxed.rs:1081:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/liballoc/boxed.rs:1081:9
      std::sys::unix:🧵:Thread:🆕:thread_start
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/libstd/sys/unix/thread.rs:87:17
  25: start_thread
  26: clone
```

2. Error

"DEBUG","fields":{"event":"consensus: Shutdown if current era is inactive","q":"Regular"},"target":"casper_node::reactor","span":{"ev":8053,"name":"dispatch events"},"spans":[{"ev":8053,"name":"crank"},{"ev":8053,"name":"dispatch events"}]}
{"timestamp":"Nov 20 22:05:00.003","level":"TRACE","fields":{"event":"Consensus(Shutdown)","q":"Regular"},"target":"casper_node::reactor","span":{"ev":8053,"name":"dispatch events"},"spans":[{"ev":8053,"name":"crank"},{"ev":8053,"name":"dispatch events"}]}

-----------------------------------

P.S. Peers was present before genesis time.

**Comment by matsuro-hadouken** [comment]
0: casper_node::panic_hook
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/libstd/panicking.rs:530:17
   3: rust_begin_unwind
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/libstd/panicking.rs:437:5
   4: std::panicking::begin_panic_fmt
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/libstd/panicking.rs:391:5
   5: casper_node::effect::EffectBuilder<REv>::fatal::{{closure}}
   6: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  10: tokio::runtime::task::raw::poll
  11: std::thread::local::LocalKey<T>::with
  12: tokio::runtime::thread_pool::worker::Context::run_task
  13: tokio::runtime::thread_pool::worker::Context::run
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
  15: tokio::runtime::thread_pool::worker::run
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  17: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::blocking::pool::Inner::run
  20: tokio::runtime::context::enter
  21: tokio::runtime::handle::Handle::enter
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: core::ops::function::FnOnce::call_once{{vtable.shim}}
  24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/liballoc/boxed.rs:1081:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/liballoc/boxed.rs:1081:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/0cd7ff7ddfb75a38dca81ad3e76b1e984129e939/src/libstd/sys/unix/thread.rs:87:17
  25: start_thread
  26: clone

panicked at 'fatal error [node/src/components/consensus/era_supervisor.rs:724]: Consensus shutting down due to inability to participate in the network', node/src/effect.rs:366:9

**Comment by matsuro-hadouken** [comment]
Just processed another restart, no success, here is full log attached.
[Uploading attached.log…]()

**Comment by goral09** [comment]
Hi @matsuro-hadouken , thank for the report.

From the logs, it looks like you start your node after the Genesis era start:
```
Shutdown if current era is inactive.
…
Consensus shutting down due to inability to participate in the network
```
In the PoS network, you cannot trust blocks created by validators you don't "know". Software detects that case and shuts down.

If you start a node after Genesis era start you have to provide a trusted hash.

**Comment by matsuro-hadouken** [comment]
@goral09 trusted hash been set in config and updated every restated mentioned above. This is why I believe here we have issue. I didn't check people logs, but we facing this every day in #node-rust chat. The way to fix this thing is just constantly update hash and restart + clean data folder in between. Is something not right, I try to catch hash on era change, but it doesn't helps much, it looks like something random is going on behind.

**Comment by goral09** [comment]
> The way to fix this thing is just constantly update hash and restart + clean data folder in between. Is something not right, I try to catch hash on era change, but it doesn't helps much, it looks like something random is going on behind.

This shouldn't be necessary anymore.

We've tried to replicate the issues with joining but it worked every time (using PCs in different geographical locations).

**Comment by MParlikar** [comment]
We have not observed this issue for quite some time, closing.
