### ISSUE TITLE
Log files invalid format

### ISSUE THREAD

**Issue by matsuro-hadouken** [CasperLabs/casper-node#597]
Periodically jq refuse to parse with the following error

`parse error: Invalid numeric literal at line ...`

This is the case of the issue:
![image](https://user-images.githubusercontent.com/50751381/100772693-d8abab80-33f7-11eb-991f-16b8851867ca.png)

Another problem I seen is this, often make `grep` thinks is a binary file

![log_issu](https://user-images.githubusercontent.com/50751381/100773040-4657d780-33f8-11eb-800c-65150ef840d4.png)

This above artifacts possible coming from incorrect log rotation.

**Comment by MParlikar** [comment]
@matsuro-hadouken could you confirm if you still see this issue?  We have done quite a bit of work on logging recently.  Closing and awaiting for you to reopen the issue.
