### ISSUE TITLE
People can't sync [ DELTA 8 ]

### ISSUE THREAD

**Issue by matsuro-hadouken** [CasperLabs/casper-node#726]
Many guys experience sync issues. I observe network and found `Scheduler Queue Total Count` constantly increasing:

![image](https://user-images.githubusercontent.com/50751381/104116840-1c0d0a00-5314-11eb-932c-13ac7957ee7b.png)

See spike on gossiper here:

![image](https://user-images.githubusercontent.com/50751381/104116856-3810ab80-5314-11eb-82f0-dcd3dfa3b5e1.png)

Which correlated with peers been joining my node and then disconnected in same frequence here:

![image](https://user-images.githubusercontent.com/50751381/104116863-4d85d580-5314-11eb-9a0e-782dbe45b775.png)

Where is also a glitch in metrics which can indecate restart of my validator unit or can be related to this issue we have presiously, where metrics with all endpoints can't be served properly and fall off periodically.

![image](https://user-images.githubusercontent.com/50751381/104116890-82922800-5314-11eb-8e64-d58f4e3db4d6.png)

* Update: 

This error recently popups in my log:

``` json
{
  "timestamp": "Jan 10 05:15:47.654",
  "level": "DEBUG",
  "fields": {
    "message": "connection error: connection closed before message completed"
  },
  "target": "hyper::server::conn::spawn_all"
}
```

**Comment by sacherjj** [comment]
Syncing fixes include PR numbers: 675, 774, 779, 782.  Delta-10 syncing shows this as fixed.
