### ISSUE TITLE
Node cant start and communicate with local api after / is full

### ISSUE THREAD

**Issue by dhinio52** [CasperLabs/casper-node#916]
I have installed casperlabs in / mountpoint. 
The node was running as  a validator and the mount point became 100% full and the node crashed. I have cleared the mount point and tried restarting the node but it fils with the below error.

CHain : Delta-10

> 
   0: casper_node::panic_hook
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/std/src/panicking.rs:493:5
   6: std::panicking::begin_panic_fmt
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/std/src/panicking.rs:435:5
   7: casper_node::effect::EffectBuilder<REv>::load_state::{{closure}}::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  11: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: tokio::runtime::task::raw::poll
  16: std::thread::local::LocalKey<T>::with
  17: tokio::runtime::thread_pool::worker::Context::run_task
  18: tokio::runtime::thread_pool::worker::Context::run
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
  20: tokio::runtime::thread_pool::worker::run
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  22: tokio::runtime::task::core::Core<T,S>::poll
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: tokio::runtime::context::enter
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/alloc/src/boxed.rs:1328:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/alloc/src/boxed.rs:1328:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/f76ecd0668fcdb289456cdc72a39ad15467cc454/library/std/src/sys/unix/thread.rs:71:17
  30: start_thread
  31: clone

**panicked at 'could not deserialize state from storage type name "core::option::Option<casper_node::components::block_proposer::deploy_sets::BlockProposerDeploySets>" err InvalidTagEncoding(61)', node/src/effect.rs:1252:13
Error: "/var/lib/casper/bin/1_0_0/casper-node" "validator" "/etc/casper/1_0_0/config.toml" exited with error**

**Comment by sacherjj** [comment]
By running the disc out of space, you have corrupted the write of local storage.

The corrective measure would be to:
`sudo systemctl stop casper-node-launcher`
`sudo /etc/casper/delete_local_db.sh`
`sudo systemctl start casper-node-launcher`

This is corruption due to server mismanagement and not handled by the node.
